<?php

namespace App\Database\Seeds;

class cmc_values extends \CodeIgniter\Database\Seeder
{
    public function run()
    {
        $data = [
            ['intrument_type_id' => '0', 'item_type_id' => '1', 'item_scope_id' => '1', 'value' => '0.27'],
            ['intrument_type_id' => '0', 'item_type_id' => '1', 'item_scope_id' => '3', 'value' => '0.87'],
            ['intrument_type_id' => '0', 'item_type_id' => '1', 'item_scope_id' => '4', 'value' => '1.5'],
            ['intrument_type_id' => '0', 'item_type_id' => '1', 'item_scope_id' => '5', 'value' => '1.8'],
            ['intrument_type_id' => '2', 'item_type_id' => '1', 'item_scope_id' => '3', 'value' => '0.86'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '6', 'value' => '0.0018'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '7', 'value' => '0.008'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '8', 'value' => '0.016'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '9', 'value' => '0.041'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '10', 'value' => '0.081'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '11', 'value' => '0.2'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '12', 'value' => '0.39'],
            ['intrument_type_id' => '0', 'item_type_id' => '2', 'item_scope_id' => '13', 'value' => '0.8'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '19', 'value' => '1.2'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '20', 'value' => '1.08'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '21', 'value' => '2.3'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '22', 'value' => '6.3'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '23', 'value' => '8.7'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '24', 'value' => '43'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '25', 'value' => '86'],
            ['intrument_type_id' => '4', 'item_type_id' => '3', 'item_scope_id' => '25', 'value' => '8.6'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '26', 'value' => '170'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '27', 'value' => '340'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '28', 'value' => '0.8'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '14', 'value' => '0.008'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '15', 'value' => '0.04'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '16', 'value' => '0.23'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '17', 'value' => '0.44'],
            ['intrument_type_id' => '0', 'item_type_id' => '3', 'item_scope_id' => '18', 'value' => '0.87'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '29', 'value' => '0.066'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '30', 'value' => '0.0078'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '31', 'value' => '0.23'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '32', 'value' => '0.44'],
            ['intrument_type_id' => '3', 'item_type_id' => '4', 'item_scope_id' => '32', 'value' => '0.43'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '33', 'value' => '0.86'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '34', 'value' => '1.7'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '39', 'value' => '43'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '40', 'value' => '86'],
            ['intrument_type_id' => '0', 'item_type_id' => '4', 'item_scope_id' => '41', 'value' => '170'],
            ['intrument_type_id' => '0', 'item_type_id' => '5', 'item_scope_id' => '43', 'value' => '1.1'],
            ['intrument_type_id' => '0', 'item_type_id' => '5', 'item_scope_id' => '44', 'value' => '6.3'],
            ['intrument_type_id' => '0', 'item_type_id' => '5', 'item_scope_id' => '45', 'value' => '8.7'],
            ['intrument_type_id' => '0', 'item_type_id' => '5', 'item_scope_id' => '46', 'value' => '21'],
            ['intrument_type_id' => '0', 'item_type_id' => '5', 'item_scope_id' => '47', 'value' => '43'],
            ['intrument_type_id' => '0', 'item_type_id' => '5', 'item_scope_id' => '48', 'value' => '86'],
            ['intrument_type_id' => '0', 'item_type_id' => '6', 'item_scope_id' => '49', 'value' => '0.78'],
            ['intrument_type_id' => '0', 'item_type_id' => '6', 'item_scope_id' => '50', 'value' => '1.1'],
            ['intrument_type_id' => '0', 'item_type_id' => '6', 'item_scope_id' => '51', 'value' => '6.3'],
            ['intrument_type_id' => '4', 'item_type_id' => '6', 'item_scope_id' => '51', 'value' => '4.03'],
            ['intrument_type_id' => '0', 'item_type_id' => '6', 'item_scope_id' => '52', 'value' => '8.7'],
            ['intrument_type_id' => '4', 'item_type_id' => '6', 'item_scope_id' => '52', 'value' => '8.6'],
            ['intrument_type_id' => '0', 'item_type_id' => '6', 'item_scope_id' => '53', 'value' => '43.0'],
            ['intrument_type_id' => '0', 'item_type_id' => '6', 'item_scope_id' => '54', 'value' => '0.4'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '55', 'value' => '0.78'],
            ['intrument_type_id' => '6', 'item_type_id' => '7', 'item_scope_id' => '55', 'value' => '0.44'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '56', 'value' => '1.08'],
            ['intrument_type_id' => '6', 'item_type_id' => '7', 'item_scope_id' => '56', 'value' => '0.87'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '57', 'value' => '2.2'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '58', 'value' => '6.3'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '58', 'value' => '4.3'],
            ['intrument_type_id' => '4', 'item_type_id' => '7', 'item_scope_id' => '58', 'value' => '4.4'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '59', 'value' => '8.6'],
            ['intrument_type_id' => '1', 'item_type_id' => '7', 'item_scope_id' => '59', 'value' => '8.7'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '60', 'value' => '43'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '61', 'value' => '86'],
            ['intrument_type_id' => '0', 'item_type_id' => '7', 'item_scope_id' => '62', 'value' => '0.4'],
            ['intrument_type_id' => '0', 'item_type_id' => '9', 'item_scope_id' => '63', 'value' => '1.10'],
            ['intrument_type_id' => '6', 'item_type_id' => '9', 'item_scope_id' => '63', 'value' => '0.87'],
            ['intrument_type_id' => '4', 'item_type_id' => '9', 'item_scope_id' => '63', 'value' => '2.2'],
            ['intrument_type_id' => '0', 'item_type_id' => '9', 'item_scope_id' => '64', 'value' => '4.4'],
            ['intrument_type_id' => '6', 'item_type_id' => '9', 'item_scope_id' => '64', 'value' => '4.3'],
            ['intrument_type_id' => '0', 'item_type_id' => '9', 'item_scope_id' => '65', 'value' => '8.6'],
            ['intrument_type_id' => '0', 'item_type_id' => '9', 'item_scope_id' => '66', 'value' => '0.8'],
            ['intrument_type_id' => '0', 'item_type_id' => '10', 'item_scope_id' => '67', 'value' => '3'],
            ['intrument_type_id' => '0', 'item_type_id' => '10', 'item_scope_id' => '68', 'value' => '6'],
            ['intrument_type_id' => '0', 'item_type_id' => '10', 'item_scope_id' => '69', 'value' => '7.9'],
            ['intrument_type_id' => '0', 'item_type_id' => '10', 'item_scope_id' => '70', 'value' => '8'],
            ['intrument_type_id' => '0', 'item_type_id' => '11', 'item_scope_id' => '71', 'value' => '8.7'],
            ['intrument_type_id' => '6', 'item_type_id' => '11', 'item_scope_id' => '71', 'value' => '8.6'],
            ['intrument_type_id' => '0', 'item_type_id' => '11', 'item_scope_id' => '72', 'value' => '86'],
            ['intrument_type_id' => '0', 'item_type_id' => '11', 'item_scope_id' => '73', 'value' => '850'],
            ['intrument_type_id' => '0', 'item_type_id' => '11', 'item_scope_id' => '74', 'value' => '8'],
            ['intrument_type_id' => '0', 'item_type_id' => '12', 'item_scope_id' => '75', 'value' => '1.9'],
            ['intrument_type_id' => '0', 'item_type_id' => '13', 'item_scope_id' => '76', 'value' => '0.06'],
            ['intrument_type_id' => '0', 'item_type_id' => '13', 'item_scope_id' => '77', 'value' => '0.1'],
            ['intrument_type_id' => '0', 'item_type_id' => '13', 'item_scope_id' => '78', 'value' => '0.2'],
            ['intrument_type_id' => '0', 'item_type_id' => '13', 'item_scope_id' => '79', 'value' => '0.4'],
            ['intrument_type_id' => '0', 'item_type_id' => '14', 'item_scope_id' => '80', 'value' => '0.1'],
            ['intrument_type_id' => '0', 'item_type_id' => '14', 'item_scope_id' => '81', 'value' => '2.1'],
            ['intrument_type_id' => '0', 'item_type_id' => '14', 'item_scope_id' => '82', 'value' => '1.9'],
            ['intrument_type_id' => '1', 'item_type_id' => '4', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '1', 'item_type_id' => '8', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '1', 'item_type_id' => '9', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '1', 'item_type_id' => '11', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '2', 'item_type_id' => '5', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '2', 'item_type_id' => '6', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '2', 'item_type_id' => '7', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '2', 'item_type_id' => '8', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '2', 'item_type_id' => '9', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '3', 'item_type_id' => '5', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '3', 'item_type_id' => '6', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '3', 'item_type_id' => '7', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '3', 'item_type_id' => '8', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '4', 'item_type_id' => '4', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '4', 'item_type_id' => '8', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '4', 'item_type_id' => '11', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '5', 'item_type_id' => '4', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '5', 'item_type_id' => '5', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '6', 'item_type_id' => '5', 'item_scope_id' => '0', 'value' => '0'],
            ['intrument_type_id' => '6', 'item_type_id' => '6', 'item_scope_id' => '0', 'value' => '0'],
        ];
        $this->db->table('cmc_values')->insertBatch($data);
    }
}
