<?php

namespace App\Database\Seeds;

class s_20210309_banks extends \CodeIgniter\Database\Seeder
{
    public function run()
    {
        $this->db->query("TRUNCATE banks");
        $data = [
            ['code' => '008', 'coa' => '1.02.00', 'name' => 'Bank Mandiri (Persero) Tbk Cab. Jakarta Cibubur', 'norek' => '129-00-1090086-4', 'currency_id' => 'IDR', 'description' => 'PT. Trusur Unggul Teknusa'],
            ['code' => '014', 'coa' => '1.02.00', 'name' => 'Bank Central Asia (BCA) Cab. Jakarta Cibubur', 'norek' => '628-0901-154', 'currency_id' => 'IDR', 'description' => 'Ayu Destina'],
            ['code' => '451', 'coa' => '1.02.00', 'name' => 'Bank Syariah Indonesia Cab. KCP Ciracas', 'norek' => '7063950925', 'currency_id' => 'IDR', 'description' => 'PT. Trusur Unggul Teknusa'],
            ['code' => '008', 'coa' => '', 'name' => 'BANK MANDIRI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '014', 'coa' => '', 'name' => 'BANK BCA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '002', 'coa' => '', 'name' => 'BANK BRI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '451', 'coa' => '', 'name' => 'BANK SYARIAH MANDIRI (BSM)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '009', 'coa' => '', 'name' => 'BANK BNI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '427', 'coa' => '', 'name' => 'BANK BNI SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '022', 'coa' => '', 'name' => 'BANK CIMB NIAGA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '022', 'coa' => '', 'name' => 'BANK CIMB NIAGA SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '147', 'coa' => '', 'name' => 'BANK MUAMALAT', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '213', 'coa' => '', 'name' => 'BANK BTPN', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '547', 'coa' => '', 'name' => 'BANK BTPN SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '213', 'coa' => '', 'name' => 'JENIUS', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '013', 'coa' => '', 'name' => 'BANK PERMATA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '013', 'coa' => '', 'name' => 'BANK PERMATA SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '046', 'coa' => '', 'name' => 'BANK DBS INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '046', 'coa' => '', 'name' => 'DIGIBANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '422', 'coa' => '', 'name' => 'BANK BRI SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '200', 'coa' => '', 'name' => 'BANK BTN', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '011', 'coa' => '', 'name' => 'BANK DANAMON', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '016', 'coa' => '', 'name' => 'BANK MAYBANK (BII)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '426', 'coa' => '', 'name' => 'BANK MEGA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '153', 'coa' => '', 'name' => 'BANK SINARMAS', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '950', 'coa' => '', 'name' => 'BANK COMMONWEALTH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '028', 'coa' => '', 'name' => 'BANK OCBC NISP', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '441', 'coa' => '', 'name' => 'BANK BUKOPIN', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '521', 'coa' => '', 'name' => 'BANK BUKOPIN SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '536', 'coa' => '', 'name' => 'BANK BCA SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '026', 'coa' => '', 'name' => 'BANK LIPPO', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '031', 'coa' => '', 'name' => 'CITIBANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '789', 'coa' => '', 'name' => 'INDOSAT DOMPETKU', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '911', 'coa' => '', 'name' => 'TELKOMSEL TCASH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '911', 'coa' => '', 'name' => 'LINKAJA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '110', 'coa' => '', 'name' => 'BANK JABAR BJB (JAWA BARAT)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '425', 'coa' => '', 'name' => 'BANK JABAR BJB SYARIAH (JAWA BARAT)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '111', 'coa' => '', 'name' => 'BANK DKI JAKARTA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '112', 'coa' => '', 'name' => 'BPD DIY (YOGYAKARTA)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '113', 'coa' => '', 'name' => 'BANK JATENG (JAWA TENGAH)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '114', 'coa' => '', 'name' => 'BANK JATIM (JAWA TIMUR)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '115', 'coa' => '', 'name' => 'BANK JAMBI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '116', 'coa' => '', 'name' => 'BANK ACEH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '116', 'coa' => '', 'name' => 'BANK ACEH SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '117', 'coa' => '', 'name' => 'BANK SUMUT', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '118', 'coa' => '', 'name' => 'BANK NAGARI (BANK SUMBAR)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '119', 'coa' => '', 'name' => 'BANK RIAU KEPRI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '120', 'coa' => '', 'name' => 'BANK SUMSEL BABEL (SUMATERA SELATAN BANGKA BELITUNG)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '121', 'coa' => '', 'name' => 'BANK LAMPUNG', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '122', 'coa' => '', 'name' => 'BANK KALSEL (BANK KALIMANTAN SELATAN)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '123', 'coa' => '', 'name' => 'BANK KALBAR (BANK KALIMANTAN BARAT)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '124', 'coa' => '', 'name' => 'BANK KALTIMTARA (BANK KALIMANTAN TIMUR DAN UTARA)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '125', 'coa' => '', 'name' => 'BANK KALTENG (BANK KALIMANTAN TENGAH)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '126', 'coa' => '', 'name' => 'BANK SULSELBAR (BANK SULAWESI SELATAN DAN BARAT)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '127', 'coa' => '', 'name' => 'BANK SULUTGO (BANK SULAWESI UTARA DAN GORONTALO)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '128', 'coa' => '', 'name' => 'BANK NTB', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '128', 'coa' => '', 'name' => 'BANK NTB SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '129', 'coa' => '', 'name' => 'BANK BPD BALI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '130', 'coa' => '', 'name' => 'BANK NTT', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '131', 'coa' => '', 'name' => 'BANK MALUKU MALUT', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '132', 'coa' => '', 'name' => 'BANK PAPUA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '133', 'coa' => '', 'name' => 'BANK BENGKULU', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '134', 'coa' => '', 'name' => 'BANK SULTENG (BANK SULAWESI TENGAH)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '135', 'coa' => '', 'name' => 'BANK SULTRA (BANK SULAWESI TENGGARA)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '137', 'coa' => '', 'name' => 'BANK BANTEN', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '003', 'coa' => '', 'name' => 'BANK EKSPOR INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '019', 'coa' => '', 'name' => 'BANK PANIN', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '517', 'coa' => '', 'name' => 'BANK PANIN DUBAI SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '020', 'coa' => '', 'name' => 'BANK ARTA NIAGA KENCANA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '023', 'coa' => '', 'name' => 'BANK UOB INDONESIA (BANK BUANA INDONESIA)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '030', 'coa' => '', 'name' => 'AMERICAN EXPRESS BANK LTD', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '031', 'coa' => '', 'name' => 'CITIBANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '032', 'coa' => '', 'name' => 'JP. MORGAN CHASE BANK, N.A.', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '033', 'coa' => '', 'name' => 'BANK OF AMERICA, N.A', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '034', 'coa' => '', 'name' => 'ING INDONESIA BANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '036', 'coa' => '', 'name' => 'BANK CCB INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '037', 'coa' => '', 'name' => 'BANK ARTHA GRAHA INTERNASIONAL', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '039', 'coa' => '', 'name' => 'BANK CREDIT AGRICOLE INDOSUEZ', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '040', 'coa' => '', 'name' => 'THE BANGKOK BANK COMP. LTD', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '042', 'coa' => '', 'name' => 'MUFG BANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '045', 'coa' => '', 'name' => 'BANK SUMITOMO MITSUI INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '047', 'coa' => '', 'name' => 'BANK RESONA PERDANIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '048', 'coa' => '', 'name' => 'BANK MIZUHO INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '050', 'coa' => '', 'name' => 'STANDARD CHARTERED BANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '052', 'coa' => '', 'name' => 'BANK ABN AMRO', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '053', 'coa' => '', 'name' => 'BANK KEPPEL TATLEE BUANA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '054', 'coa' => '', 'name' => 'BANK CAPITAL INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '057', 'coa' => '', 'name' => 'BANK BNP PARIBAS INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '023', 'coa' => '', 'name' => 'BANK UOB INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '059', 'coa' => '', 'name' => 'KOREA EXCHANGE BANK DANAMON', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '060', 'coa' => '', 'name' => 'RABOBANK INTERNASIONAL INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '061', 'coa' => '', 'name' => 'BANK ANZ INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '069', 'coa' => '', 'name' => 'BANK OF CHINA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '076', 'coa' => '', 'name' => 'BANK BUMI ARTA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '087', 'coa' => '', 'name' => 'BANK HSBC INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '087', 'coa' => '', 'name' => 'BANK EKONOMI (Lebur dengan Bank HSBC)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '088', 'coa' => '', 'name' => 'BANK ANTARDAERAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '089', 'coa' => '', 'name' => 'BANK HAGA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '093', 'coa' => '', 'name' => 'BANK IFI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '095', 'coa' => '', 'name' => 'BANK J TRUST INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '097', 'coa' => '', 'name' => 'BANK MAYAPADA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '145', 'coa' => '', 'name' => 'BANK NUSANTARA PARAHYANGAN', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '146', 'coa' => '', 'name' => 'BANK SWADESI (BANK OF INDIA INDONESIA)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '151', 'coa' => '', 'name' => 'BANK MESTIKA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '152', 'coa' => '', 'name' => 'BANK SHINHAN INDONESIA (BANK METRO EXPRESS)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '157', 'coa' => '', 'name' => 'BANK MASPION INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '159', 'coa' => '', 'name' => 'BANK HAGAKITA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '161', 'coa' => '', 'name' => 'BANK GANESHA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '162', 'coa' => '', 'name' => 'BANK WINDU KENTJANA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '164', 'coa' => '', 'name' => 'BANK ICBC INDONESIA (HALIM INDONESIA BANK)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '166', 'coa' => '', 'name' => 'BANK HARMONI INTERNATIONAL', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '167', 'coa' => '', 'name' => 'BANK QNB INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '212', 'coa' => '', 'name' => 'BANK WOORI SAUDARA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '405', 'coa' => '', 'name' => 'BANK VICTORIA SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '459', 'coa' => '', 'name' => 'BANK BISNIS INTERNASIONAL', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '466', 'coa' => '', 'name' => 'BANK SRI PARTHA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '472', 'coa' => '', 'name' => 'BANK JASA JAKARTA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '484', 'coa' => '', 'name' => 'BANK HANA (KEB HANA BANK)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '485', 'coa' => '', 'name' => 'BANK MNC', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '490', 'coa' => '', 'name' => 'BANK YUDHA BHAKTI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '491', 'coa' => '', 'name' => 'BANK MITRANIAGA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '494', 'coa' => '', 'name' => 'BANK BRI AGRO', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '498', 'coa' => '', 'name' => 'BANK SBI INDONESIA (BANK INDOMONEX)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '501', 'coa' => '', 'name' => 'BANK DIGITAL BCA (BCA DIGITAL)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '503', 'coa' => '', 'name' => 'BANK NATIONAL NOBU (BANK ALFINDO)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '506', 'coa' => '', 'name' => 'BANK MEGA SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '513', 'coa' => '', 'name' => 'BANK INA PERDANA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '517', 'coa' => '', 'name' => 'BANK PANIN DUBAI SYARIAH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '520', 'coa' => '', 'name' => 'PRIMA MASTER BANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '521', 'coa' => '', 'name' => 'BANK PERSYARIKATAN INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '525', 'coa' => '', 'name' => 'BANK AKITA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '526', 'coa' => '', 'name' => 'BANK DINAR INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '531', 'coa' => '', 'name' => 'ANGLOMAS INTERNASIONAL BANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '523', 'coa' => '', 'name' => 'BANK SAHABAT SAMPEORNA (BANK DIPO INTERNATIONAL)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '535', 'coa' => '', 'name' => 'BANK KESEJAHTERAAN EKONOMI', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '542', 'coa' => '', 'name' => 'BANK ARTOS INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '548', 'coa' => '', 'name' => 'BANK MULTIARTA SENTOSA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '553', 'coa' => '', 'name' => 'BANK MAYORA INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '555', 'coa' => '', 'name' => 'BANK INDEX SELINDO', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '558', 'coa' => '', 'name' => 'BANK EKSEKUTIF', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '559', 'coa' => '', 'name' => 'CENTRATAMA NASIONAL BANK', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '562', 'coa' => '', 'name' => 'BANK FAMA INTERNASIONAL', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '564', 'coa' => '', 'name' => 'BANK MANDIRI TASPEN POS (BANK SINAR HARAPAN BALI)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '566', 'coa' => '', 'name' => 'BANK VICTORIA INTERNATIONAL', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '567', 'coa' => '', 'name' => 'BANK HARDA INTERNASIONAL', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '945', 'coa' => '', 'name' => 'IBK BANK INDONESIA', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '946', 'coa' => '', 'name' => 'BANK MERINCORP', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '947', 'coa' => '', 'name' => 'BANK MAYBANK INDOCORP', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '949', 'coa' => '', 'name' => 'BANK CTBC INDONESIA (CHINA TRUST)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '950', 'coa' => '', 'name' => 'BANK COMMONWEALTH', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],
            ['code' => '688', 'coa' => '', 'name' => 'BPR KS (KARYAJATNIKA SEDAYA)', 'norek' => '', 'currency_id' => 'IDR', 'description' => ''],

        ];
        $this->db->table('banks')->insertBatch($data);
    }
}
